# Generated by Django 4.0.6 on 2022-07-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='about_me',
            field=models.TextField(null=True),
        ),
    ]
