# Generated by Django 4.0.6 on 2022-07-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chairman_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=20, null=True)),
                ('block_no', models.CharField(max_length=10, null=True)),
                ('house_no', models.CharField(max_length=10, null=True)),
                ('family_mem', models.IntegerField(null=True)),
                ('total_vehicle', models.IntegerField(null=True)),
                ('pic', models.FileField(default='media/default_chairman.png', upload_to='media/images/')),
                ('about_member', models.TextField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
